image: nixos/latest
packages:
  - nixos.racket
sources:
  - https://git.sr.ht/~yilin/raco-search
tasks:
  - build: |
      cd raco-search
      raco pkg install --auto
  - test: |
      raco test raco-search